version: '3.7'

services:
  friznet_back:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
  friznet_db:
    image: postgres:12.0-alpine
    volumes:
      - friznet_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=frizmnet_user
      - POSTGRES_PASSWORD=friznet_pass
      - POSTGRES_DB=friznet

  volumes:
    friznet_postgres_data:
